### ISSUE TITLE
Do "until first milestone" Part of Project Plan by Using Project Libre

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#101]
Deadline: 15.04.2022 17.59

TODO:
- [x] Do "until first milestone" Part of Project Plan by Using Project Libre.
- [x] Enter  start and dates of jobs at "until first milestone" of project plan.
- [x] Assign human resources to jobs at "until first milestone" of project plan.
