### ISSUE TITLE
Creating necessary place for Plan, RAM, and Milestone

### ISSUE THREAD

**Issue by berkkant** [bounswe/bounswe2022group9#109]
TODO:

- [x]  Create place for Plan

- [x]  Create place for RAM

- [x]  Create place for Milestone

**Comment by berkkant** [comment]
Done.
