### ISSUE TITLE
[Milestone] Creating Pre-Release version of project

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#288]
Deadline: 01.11.2022 11.59

TODO:

- [x] A Pre-Release with name 0.1.0-alpha will be created.
- [x] A brief description will be added according to requirements.
- [x]  A tag with name customer-presentation-1 will be added.

**Comment by ozdemirfurkan** [comment]
Pre-release is created with given tag. A brief description is added.
