### ISSUE TITLE
[Milestone] Creating report for deliverables.

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#289]
Deadline: 01.11.2022 11.59

TODO:

- [x] A directory named customer_presentation_milestone_1 will be created.
- [x] A file named Deliverables.md will be created to report all deliverable documents.
- [x] Hyperlinks for requirements, UML designs, scenarios and mock-ups will be added.
- [x] Each member will create and link his/her individual contribution reports.

**Comment by omersisman** [comment]
The directory [customer_presentation_milestone_1](https://github.com/bounswe/bounswe2022group9/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_1) is created.

**Comment by omersisman** [comment]
The file named [Deliverables](https://github.com/bounswe/bounswe2022group9/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/Deliverables.md) is created.

**Comment by omersisman** [comment]
Me, Burak Ferit and Buğra have linked individual contribution reports. The issue will be closed when everyone added his/her individual contribution report.

**Comment by utulb** [comment]
I have linked the individual contribution reports and made additions to the milestone report file.
