### ISSUE TITLE
Create "Evaluation of Tools" part of the Milestone 1

### ISSUE THREAD

**Issue by berkkant** [bounswe/bounswe2022group9#316]
In the milestone, we have to create evaluation part of the milestone 1.

- [x] Analyze backend system
- [x] Research on the tools that are used
- [x] Add the evaluation to the milestone 1

**Comment by berkkant** [comment]
All the tasks are done.
