### ISSUE TITLE
[Milestone] Prepare Executive Summary For the Final Milestone

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#546]
Deadline: 02.01.2022 23.59

As mentioned in the [Final milestone PDF in the Moodle](https://moodle.boun.edu.tr/mod/resource/view.php?id=674587) , one of the important deliverables for the final milestone is the "Executive Summary" part of "Group Milestone Report".

The "Executive Summary" part of the Group Milestone Report, should include the followings (I'm adding an image from the final milestone pdf):
![image](https://user-images.githubusercontent.com/61063293/210139326-c1fffe49-dff6-4e47-a0a2-63494c58a42a.png)

TODO:
- [x] Create a file for Group Milestone report under [deliverables folder](https://github.com/bounswe/bounswe2022group9/tree/master/deliverables)
- [x] Write a summary of the status of the project
- [x] Explain the status of deliverables
- [x] Write final release notes
- [x] Write reflections and lessons learned from the Final Milestone Demo
- [x] Mention what can be done differently if we were to start the project from beginning again, with reasons
- [x] Explain the changes made in the development process and their effect

**Comment by burakaktan** [comment]
All elemnets in the the TODO list are marked as complete.
[Executive Summary can be reached from here](https://github.com/bounswe/bounswe2022group9/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_Final/Milestone_Group_Review.md#a-executive-summary)
