### ISSUE TITLE
[Milestone] Prepare Individual Report 

### ISSUE THREAD

**Issue by ozdemirfurkan** [bounswe/bounswe2022group9#547]
Deadline: 02.01.2022 23.59

As mentioned in the [Final milestone PDF in the Moodle](https://moodle.boun.edu.tr/mod/resource/view.php?id=674587) , each group member should create an individual report which consists the contributions for final milestone.

TODO:
- [x] Create a file for Individual Report under [deliverables folder](https://github.com/bounswe/bounswe2022group9/tree/master/deliverables)
- [x] Explain the contributions for final milestone.
- [x] Document the issues and pull requests.

**Comment by ozdemirfurkan** [comment]
[The individual report](https://github.com/bounswe/bounswe2022group9/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/individual_contributions_reports/Furkan_Ozdemir.md) is created and issues are documented.
