### ISSUE TITLE
[Milestone] Prepare Individual Contributions Report for Burak Ferit Aktan

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#550]
Deadline: 02.01.2022 23.59

As mentioned in the [Final milestone PDF in the Moodle](https://moodle.boun.edu.tr/mod/resource/view.php?id=674587) , each group member should create an individual contributions report which consists the contributions for final milestone.

These individual contributions report should include: member information, responsibilities, code related significant issues, management related significant issues, pull requests and unit tests.

TODO:
- [x] Create a file for Individual Report under [deliverables folder](https://github.com/bounswe/bounswe2022group9/tree/master/deliverables)
- [x] Give member information including name, group, subgroup
- [x] Document your responsibilities
- [x] List code related significant issues and give links to the issues
- [x] List management related significant issues and give links to the issues
- [x] List pull requests and links to them
- [x] Mention unit tests written

**Comment by burakaktan** [comment]
All items in the TODO list are done.

[The Individual Contributions Report can be reached from here](https://github.com/bounswe/bounswe2022group9/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/individual_contributions_reports/Burak_Ferit_Aktan.md)

As a result, the issue can be closed.
