### ISSUE TITLE
[Milestone] Prepare Individual Contributions Report for Ömer Faruk Şişman

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#553]
Deadline: 02.01.2022 23.59

As mentioned in the [Final milestone PDF in the Moodle](https://moodle.boun.edu.tr/mod/resource/view.php?id=674587) , each group member should create an individual contributions report which consists the contributions for final milestone.

These individual contributions report should include: member information, responsibilities, code related significant issues, management related significant issues, pull requests and unit tests.

TODO:
- [x] Give member information including name, group, subgroup
- [x] Document your responsibilities
- [x] List code related significant issues and give links to the issues
- [x] List management related significant issues and give links to the issues
- [x] List pull requests and links to them
- [x] Mention unit tests written
