### ISSUE TITLE
Reviewing Milestone report 1

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#98]
Deadline: 15.04.2022 18.59

TODO:

- [ ] Reviewing all parts of the milestone 1 by everyone to control works of each other.
- [ ] Removing conflicts from the milestone report.
- [ ] Preparing the final version to be submitted by communicator.
